# Generated by Django 4.2.4 on 2023-08-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_memory_max',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_symbol', models.CharField(max_length=100)),
                ('_price_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo_memory_min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_symbol', models.CharField(max_length=100)),
                ('_price_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo_memory_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_symbol', models.CharField(max_length=255)),
                ('_quant', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_memory_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_transaction', models.CharField(max_length=100)),
                ('_operation', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=10)),
                ('_quant', models.PositiveIntegerField()),
                ('_price_now', models.FloatField()),
                ('_price_min', models.FloatField()),
                ('_price_max', models.FloatField()),
                ('_date', models.DateTimeField(auto_now_add=True)),
                ('_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memory.modelo_memory_wallet')),
            ],
        ),
    ]
