# Generated by Django 4.2.4 on 2023-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_memory_max',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_symbol', models.CharField(max_length=100)),
                ('_price_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo_memory_min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_symbol', models.CharField(max_length=100)),
                ('_price_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo_memory_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_symbol', models.CharField(max_length=100)),
                ('_price_min', models.FloatField()),
                ('_price_now', models.FloatField()),
                ('_quant', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='modelo_memory_goal',
        ),
        migrations.DeleteModel(
            name='modelo_memory_obstacle',
        ),
        migrations.DeleteModel(
            name='modelo_memory_robot',
        ),
    ]
